CREATE TABLE notification (
	id BIGSERIAL NOT NULL,
	event_id BIGINT NOT NULL REFERENCES events(id) ON DELETE CASCADE,
	user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
	notification_time TIMESTAMP NOT NULL,
	is_sent BOOLEAN NOT NULL DEFAULT FALSE
);